const hackathonData = [
  {
    title: "Microsoft Fabric and AI Learning Hackathon",
    timeLeft: "12 days left",
    location: "Online",
    prize: "$10,000",
    participants: "4163 participants",
    tags: ["Beginner Friendly", "Databases", "Machine Learning/AI"],
    description: "An exciting hackathon to explore Microsoft Fabric and AI technologies.",
    imageUrl: "https://images.pexels.com/photos/10142683/pexels-photo-10142683.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    title: "Google Chrome Built-in AI Challenge",
    timeLeft: "About 1 month left",
    location: "Online",
    prize: "$65,000",
    participants: "3799 participants",
    tags: ["Machine Learning/AI", "Web", "Beginner Friendly"],
    description: "Join the challenge to innovate with AI in Google Chrome.",
    imageUrl: "https://images.pexels.com/photos/5494323/pexels-photo-5494323.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    title: "She Builds AI",
    timeLeft: "13 days left",
    location: "Online",
    prize: "$15,000",
    participants: "2000 participants",
    tags: ["Social Good", "AI", "Women in Tech"],
    description: "Empower women in tech through AI development.",
    imageUrl: "https://images.pexels.com/photos/6153354/pexels-photo-6153354.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    title: "Tech for Good Hackathon",
    timeLeft: "7 days left",
    location: "Online",
    prize: "$25,000",
    participants: "1500 participants",
    tags: ["Social Good", "Web Development", "Hack for Good"],
    description: "Join the movement to use technology for social impact.",
    imageUrl: "https://images.unsplash.com/photo-1638029202288-451a89e0d55f?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    title: "AI for Healthcare Innovation",
    timeLeft: "20 days left",
    location: "Online",
    prize: "$50,000",
    participants: "3000 participants",
    tags: ["AI", "Healthcare", "Beginner Friendly"],
    description: "Work on AI solutions that can transform healthcare.",
    imageUrl: "https://images.pexels.com/photos/6153740/pexels-photo-6153740.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    title: "Women in Tech Hackathon",
    timeLeft: "25 days left",
    location: "Online",
    prize: "$30,000",
    participants: "2200 participants",
    tags: ["Women in Tech", "Social Good", "Tech for Good"],
    description: "A platform for women to build innovative solutions.",
    imageUrl: "https://images.pexels.com/photos/1181260/pexels-photo-1181260.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    title: "Blockchain for Change",
    timeLeft: "5 days left",
    location: "Online",
    prize: "$40,000",
    participants: "1200 participants",
    tags: ["Blockchain", "Social Good", "Beginner Friendly"],
    description: "Create blockchain solutions that promote positive change.",
    imageUrl: "https://images.pexels.com/photos/730547/pexels-photo-730547.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    title: "Hack for Earth",
    timeLeft: "3 days left",
    location: "Online",
    prize: "$20,000",
    participants: "5000 participants",
    tags: ["Sustainability", "Social Good", "Environmental Tech"],
    description: "Develop tech solutions that help save the planet.",
    imageUrl: "https://images.pexels.com/photos/29465453/pexels-photo-29465453/free-photo-of-pitchfork-lying-on-dirt-path-in-mendoza-argentina.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    title: "Open AI Code Sprint",
    timeLeft: "18 days left",
    location: "Online",
    prize: "$15,000",
    participants: "4000 participants",
    tags: ["Machine Learning", "AI", "Code Sprint"],
    description: "Compete in a fast-paced coding environment focused on AI.",
    imageUrl: "https://images.pexels.com/photos/6153740/pexels-photo-6153740.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    title: "Eco-Tech Hackathon",
    timeLeft: "10 days left",
    location: "Online",
    prize: "$20,000",
    participants: "3000 participants",
    tags: ["Sustainability", "Environmental Tech"],
    description: "Innovate with technology to protect our planet.",
    imageUrl: "https://images.pexels.com/photos/10142683/pexels-photo-10142683.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    title: "AI Game Jam",
    timeLeft: "15 days left",
    location: "Online",
    prize: "$10,000",
    participants: "3500 participants",
    tags: ["Game Development", "AI", "Interactive"],
    description: "Combine game design and AI in this creative hackathon.",
    imageUrl: "https://images.pexels.com/photos/5494323/pexels-photo-5494323.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    title: "Future of Work Hackathon",
    timeLeft: "8 days left",
    location: "Online",
    prize: "$12,000",
    participants: "2000 participants",
    tags: ["AI", "Productivity", "Remote Work"],
    description: "Build tools and solutions for the future of work.",
    imageUrl: "https://images.pexels.com/photos/6153354/pexels-photo-6153354.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
];

export default hackathonData;
